version: "3.9"

services:
  web:
    image: php:8.2-apache
    container_name: lamp_web
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - lamp_net

  db:
    image: mysql:8.0
    container_name: lamp_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: myapp
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - lamp_net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: lamp_phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_USER: user
      PMA_PASSWORD: userpass
      PMA_ARBITRARY: 1
    ports:
      - "8081:80"
    depends_on:
      - db
    networks:
      - lamp_net

networks:
  lamp_net:
    driver: bridge
