version: "3.8"
services:
  app_proxy:
    image: getumbrel/app-proxy:latest
    environment:
      APP_HOST: web
      APP_PORT: 80
    restart: always

  web:
    image: php:8.3-apache
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/www:/var/www/html
    depends_on: [db]

  db:
    image: mysql:8.0
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: supergeheim123
      MYSQL_DATABASE: lamp
      MYSQL_USER: lamp
      MYSQL_PASSWORD: lamp123
    volumes:
      - ${APP_DATA_DIR}/db:/var/lib/mysql